name: Feature Request
description: This project thrives from differentiation from competing apps. Suggest an idea for Anime Preview
labels: [feature request]
body:
  - type: textarea
    attributes:
      label: What's the Problem?
      description: If your feature request is related to a problem, describe it clearly.
  - type: textarea
    attributes:
      label: Solution/Idea
      description: Describe your solution/idea.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        Please include a list of what the feature should and shouldn't do by filling in the table below.

        'Must' implies that the feature should not ship without this capability.
        'Should' is something we should push hard for, but is not absolutely required to ship.
        'Could' is a nice-to-have; a good stretch goal that isn't painful if we don't achieve it.
        'Won't' is a clear statement that the proposal/feature will intentionally not have that capability.

        This list will evolve and grow as the proposal becomes more refined over time.
        A good rule of thumb is to start your proposal with no more than 7 high-level requirements.
  - type: textarea
    attributes:
      label: Priorities
      description: describe all the elements of your idea and how important they are.
      value: |
        | Capability | Priority |
        | :---------- | :------- |
        | This proposal will allow developers to accomplish W | Must |
        | This proposal will allow end users to accomplish X | Should |
        | This proposal will allow developers to accomplish Y | Could |
        | This proposal will allow end users to accomplish Z | Won't |
  - type: input
    id: anime-preview-version
    attributes:
      label: Anime Preview Version
      description: Which version of Anime Preview are you using?
      placeholder: v0.1
    validations:
      required: true
  - type: input
    attributes:
      label: OS Version
      description: Which system are you using? Please also indicate its version.
      placeholder: e.g. Windows 11 21H2 22000.194
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional comment
      description: Add any other comments or screenshots about the feature request here. What device type/UI layout and app version?